# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Tag.destroy_all
City.destroy_all

Tag.create(name: "Sunny")
Tag.create(name: "Clear")
Tag.create(name: "Cloudy")
Tag.create(name: "Rain")
Tag.create(name: "Snow")
Tag.create(name: "Storm")
Tag.create(name: "Freezing (Under 40F)")
Tag.create(name: "Cold (40F - 49F)")
Tag.create(name: "Chilly (50F - 59F)")
Tag.create(name: "Cool (60F - 67F)")
Tag.create(name: "Warm (68F - 75F)")
Tag.create(name: "Hot (76F - 85F)")
Tag.create(name: "Arizona (86F and Over)")




City.create(name: 'Tokyo')
City.create(name: 'Delhi')
City.create(name: 'Shanghai')
City.create(name: 'Sao Paulo')
City.create(name: 'Mexico City')
City.create(name: 'Cairo')
City.create(name: 'Mumbai')
City.create(name: 'Beijing')
City.create(name: 'Dhaka')
City.create(name: 'Osaka')
City.create(name: 'New York City')
City.create(name: 'Karachi')
City.create(name: 'Buenos Aires')
City.create(name: 'Chongqing')
City.create(name: 'Istanbul')
City.create(name: 'Kolkata')
City.create(name: 'Manila')
City.create(name: 'Lagos')
City.create(name: 'Rio de Janeiro')
City.create(name: 'Tianjin')
City.create(name: 'Kinshasa')
City.create(name: 'Guangzhou')
City.create(name: 'Los Angeles')
City.create(name: 'Moscow')
City.create(name: 'Shenzhen')
City.create(name: 'Lahore')
City.create(name: 'Bangalore')
City.create(name: 'Paris')
City.create(name: 'London')
City.create(name: 'Bogota')
City.create(name: 'Jakarta')
City.create(name: 'Chennai')
City.create(name: 'Bangkok')
City.create(name: 'Seoul')
City.create(name: 'Chicago')
City.create(name: 'Wuhan')
City.create(name: 'Xian')
City.create(name: 'Madrid')
City.create(name: 'Barcelona')
City.create(name: 'Toronto')
City.create(name: 'Miami')
City.create(name: 'Johannesburg')
City.create(name: 'Washington D.C.')